services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DEBUG=${DEBUG:-False}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      # Mount the backend directory for development
      - ./backend:/app

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:


