# Generated by Django 5.1.6 on 2025-08-02 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brokerage_name', models.CharField(choices=[('webull', 'Webull'), ('robinhood', 'Robinhood'), ('ibkr', 'Interactive Brokers (IBKR)'), ('charles_schwab', 'Charles Schwab'), ('fidelity', 'Fidelity'), ('moomoo', 'Moomoo'), ('sofi', 'SoFi'), ('etrade', 'E-Trade'), ('etoro', 'eToro'), ('tradestation', 'TradeStation'), ('coinbase', 'Coinbase')], max_length=50)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('buying_power', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'brokerage_name')},
            },
        ),
        migrations.CreateModel(
            name='BrokerageSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_frequency_hours', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('price_alerts_enabled', models.BooleanField(default=True)),
                ('portfolio_alerts_enabled', models.BooleanField(default=True)),
                ('transaction_notifications_enabled', models.BooleanField(default=True)),
                ('share_portfolio_data', models.BooleanField(default=False)),
                ('share_transaction_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('webhook_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='brokerage_integrations.brokerageaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='brokerage_integrations.brokerageaccount')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token'), ('api_key', 'API Key'), ('secret', 'Secret Key')], max_length=20)),
                ('token_value', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='brokerage_integrations.brokerageaccount')),
            ],
            options={
                'unique_together': {('account', 'token_type')},
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unrealized_pnl_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='brokerage_integrations.brokerageaccount')),
            ],
            options={
                'ordering': ['-market_value'],
                'unique_together': {('account', 'symbol')},
            },
        ),
    ]
